# Generated by Django 5.2 on 2025-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='data_avaliacao',
        ),
        migrations.RemoveField(
            model_name='lojafavorita',
            name='data_favorito',
        ),
        migrations.RemoveField(
            model_name='totempesquisa',
            name='data',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.FloatField(),
        ),
    ]
