# Generated by Django 5.2 on 2025-05-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('mapa', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('loja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapas_lojas', to='app.loja')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
