# Generated by Django 5.2 on 2025-05-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cliente_faixa_etaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='categoria',
        ),
        migrations.AddField(
            model_name='cliente',
            name='categorias_desejadas',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='app.categoria'),
        ),
    ]
