# Generated by Django 5.2 on 2025-04-30 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_avaliacao_data_avaliacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='app.setor'),
        ),
    ]
