# Generated by Django 5.2 on 2025-05-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mapas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lojista',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lojista',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='lojista',
            name='senha',
        ),
    ]
