# Generated by Django 5.2 on 2025-05-05 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cliente_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='url_video',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='lojas',
        ),
        migrations.AddField(
            model_name='loja',
            name='categorias',
            field=models.ManyToManyField(related_name='lojas', to='app.categoria'),
        ),
        migrations.AddField(
            model_name='loja',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='app.setor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='faixa_etaria',
            field=models.CharField(choices=[('18-', '18-'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('56-65', '56-65'), ('65+', '65+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='totempessoal',
            name='faixa_etaria',
            field=models.CharField(choices=[('18-', '18-'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('56-65', '56-65'), ('65+', '65+')], max_length=10),
        ),
    ]
