# Generated by Django 5.2 on 2025-05-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_lojista_email_remove_lojista_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lojista',
            name='user',
        ),
    ]
