# Generated by Django 5.2 on 2025-04-30 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_setor_categoria_alter_categoria_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='app.categoria'),
        ),
    ]
