# Generated by Django 5.2 on 2025-04-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_setor_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='loja',
        ),
        migrations.AddField(
            model_name='loja',
            name='produtos',
            field=models.ManyToManyField(related_name='lojas', to='app.produto'),
        ),
    ]
