# Generated by Django 5.2 on 2025-05-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_produto_categoria_produto_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='totempessoal',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesquisas_totem', to='app.categoria'),
        ),
        migrations.DeleteModel(
            name='TotemPesquisa',
        ),
    ]
