# Generated by Django 5.2 on 2025-04-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_produto_loja_loja_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='categoria',
        ),
        migrations.AddField(
            model_name='setor',
            name='categorias',
            field=models.ManyToManyField(related_name='setores', to='app.categoria'),
        ),
    ]
