# Generated by Django 5.2 on 2025-05-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_lojista_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojista',
            name='nome',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
