# Generated by Django 5.2 on 2025-05-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_acaousuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='redes_sociais',
            new_name='Instagram',
        ),
        migrations.AddField(
            model_name='loja',
            name='Website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='WhatsApp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
