# Generated by Django 5.2 on 2025-05-28 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_redes_sociais_loja_instagram_loja_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='produtos',
        ),
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app.loja'),
            preserve_default=False,
        ),
    ]
