# Generated by Django 5.2 on 2025-06-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_loja_produtos_produto_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
