# Generated by Django 5.2 on 2025-06-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cliente_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lojista',
            old_name='cpf_cnpj',
            new_name='cnpj',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='faixa_etaria',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lojista',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
